/// Integration tests that simulate REAL user interaction with the Drawer.
///
/// These tests tap the hamburger icon, drawer menu items, and notification
/// button exactly as a human user would -- using [tester.tap()] on actual
/// widgets instead of [ScaffoldState.openDrawer()].
///
/// Two groups:
///   1. Drawer UI interaction tests (tap hamburger, tap menu items, navigate)
///   2. Full ProviderScope bootstrap test (mirrors main.dart setup)
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:egranja_flutter/core/auth/auth_service.dart';
import 'package:egranja_flutter/core/router/app_router.dart';
import 'package:egranja_flutter/core/router/route_names.dart';
import 'package:egranja_flutter/core/sync/sync_state.dart';
import 'package:egranja_flutter/core/theme/app_theme.dart';
import 'package:egranja_flutter/features/auth/presentation/providers/auth_provider.dart';
import 'package:egranja_flutter/features/notifications/presentation/providers/alertas_provider.dart';

// ── Fake Notifiers (same pattern as router_navigation_test.dart) ──────────

class FakeAuthNotifier extends StateNotifier<AuthState>
    implements AuthNotifier {
  FakeAuthNotifier(super.initial);

  @override
  Future<void> login(String username, String password) async {}
  @override
  Future<String?> register({
    required String nome,
    required String email,
    required String telefone,
    required String senha,
    required String tipo,
  }) async =>
      null;
  @override
  Future<void> logout() async {
    state = const AuthState(status: AuthStatus.unauthenticated);
  }

  @override
  Future<String?> forgotPassword(String email) async => null;
  @override
  Future<void> checkAuth() async {}
  @override
  void clearError() {}
}

class FakeAlertasNotifier extends StateNotifier<AlertasState>
    implements AlertasNotifier {
  FakeAlertasNotifier() : super(const AlertasState());

  @override
  Future<void> fetchAlertas() async {}
  @override
  Future<void> refresh() async {}
}

// ── Test Helpers ──────────────────────────────────────────────────────────

const _testUser = User(
  id: 'user-123',
  login: 'produtor1',
  nome: 'Produtor Teste',
  tipo: 'produtor',
);

const _testTecnico = User(
  id: 'tecnico-456',
  login: 'tecnico1',
  nome: 'Tecnico Teste',
  tipo: 'tecnico',
);

ProviderContainer _createContainer({
  AuthState? authState,
  int alertCount = 0,
}) {
  final effectiveAuthState = authState ??
      const AuthState(
        status: AuthStatus.authenticated,
        user: _testUser,
      );

  return ProviderContainer(
    overrides: [
      authNotifierProvider
          .overrideWith((_) => FakeAuthNotifier(effectiveAuthState)),
      alertasProvider.overrideWith((_) => FakeAlertasNotifier()),
      alertasCountProvider.overrideWith((ref) => alertCount),
      syncProvider.overrideWith((_) => SyncNotifier(null)),
    ],
  );
}

Widget _createTestApp(ProviderContainer container) {
  final router = container.read(goRouterProvider);
  return UncontrolledProviderScope(
    container: container,
    child: MaterialApp.router(routerConfig: router),
  );
}

/// Creates the app using the SAME structure as main.dart:
///   ProviderScope → EGranjaApp (Consumer → MaterialApp.router)
///
/// This catches provider chain errors that only happen in production
/// when providers are resolved lazily through the full tree.
Widget _createFullBootstrapApp(List<Override> overrides) {
  return ProviderScope(
    overrides: overrides,
    child: Consumer(
      builder: (context, ref, _) {
        final router = ref.read(goRouterProvider);
        return MaterialApp.router(
          title: 'eGranja',
          theme: AppTheme.lightTheme,
          routerConfig: router,
          debugShowCheckedModeBanner: false,
        );
      },
    ),
  );
}

/// Sets a larger viewport to prevent overflow in widget tests.
void _useWideViewport(WidgetTester tester) {
  tester.view.physicalSize = const Size(1200, 1800);
  tester.view.devicePixelRatio = 1.0;
  addTearDown(() {
    tester.view.resetPhysicalSize();
    tester.view.resetDevicePixelRatio();
  });
}

/// Pumps the widget and waits for route transitions to settle.
Future<void> _pumpAndSettle(WidgetTester tester) async {
  await tester.pump();
  await tester.pump(const Duration(milliseconds: 500));
}

/// Taps the hamburger icon and waits for the drawer to open.
///
/// Searches for the DrawerButton (auto-generated by Scaffold when drawer
/// is present) or falls back to Icons.menu. This is what a real user taps.
Future<void> _tapHamburgerIcon(WidgetTester tester) async {
  // Flutter's Scaffold auto-generates a DrawerButton with a tooltip
  final drawerButton = find.byTooltip('Open navigation menu');
  if (drawerButton.evaluate().isNotEmpty) {
    await tester.tap(drawerButton);
  } else {
    // Fallback: tap the menu icon directly
    await tester.tap(find.byIcon(Icons.menu));
  }
  await tester.pump();
  await tester.pump(const Duration(milliseconds: 300));
}

// ── Tests: Drawer UI Interaction ─────────────────────────────────────────

void main() {
  group('Drawer Integration - Real User Interaction', () {
    late ProviderContainer container;

    setUp(() {
      container = _createContainer();
    });

    tearDown(() {
      container.dispose();
    });

    testWidgets(
      'Tapping hamburger icon opens the drawer with menu items',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        // Verify we start on Home
        expect(find.text('eGranja'), findsOneWidget);

        // Tap the hamburger icon -- like a real user would
        await _tapHamburgerIcon(tester);

        // Verify drawer content appears
        expect(find.byType(Drawer), findsOneWidget);
        expect(find.text('Inicio'), findsOneWidget);
        expect(find.text('Checklist Diario'), findsOneWidget);
        expect(find.text('Granjas'), findsOneWidget);
        expect(find.text('Alertas'), findsOneWidget);
        expect(find.text('Sair'), findsOneWidget);
      },
    );

    testWidgets(
      'Tapping "Granjas" in drawer navigates to Granjas page',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        // Open drawer by tapping hamburger
        await _tapHamburgerIcon(tester);

        // Scroll to make "Granjas" visible and tap it
        final granjasFinder = find.text('Granjas');
        await tester.ensureVisible(granjasFinder);
        await tester.tap(granjasFinder);
        await _pumpAndSettle(tester);

        // Verify navigation happened: title should be "Granjas"
        expect(find.text('Granjas'), findsWidgets);
      },
    );

    testWidgets(
      'Navigate to Granjas via drawer, then open drawer again and go to Checklist',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        // --- First navigation: Home → Granjas ---
        await _tapHamburgerIcon(tester);
        final granjasFinder = find.text('Granjas');
        await tester.ensureVisible(granjasFinder);
        await tester.tap(granjasFinder);
        await _pumpAndSettle(tester);

        // Verify we are on Granjas
        expect(find.text('Granjas'), findsWidgets);

        // --- Second navigation: Granjas → Checklist ---
        await _tapHamburgerIcon(tester);
        final checklistFinder = find.text('Checklist Diario');
        await tester.ensureVisible(checklistFinder);
        await tester.tap(checklistFinder);
        await _pumpAndSettle(tester);

        // Verify we navigated to Checklist
        expect(find.text('Checklist Diario'), findsWidgets);
      },
    );

    testWidgets(
      'Tapping notification icon navigates to Alertas without errors',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        // Tap the notification bell icon in the AppBar -- real user interaction
        await tester.tap(find.byIcon(Icons.notifications_outlined).first);
        await _pumpAndSettle(tester);

        // Should navigate to Alertas screen
        expect(find.text('Alertas'), findsWidgets);
      },
    );

    testWidgets(
      'Notification badge appears when alertCount > 0',
      (tester) async {
        _useWideViewport(tester);
        final badgeContainer = _createContainer(alertCount: 5);
        await tester.pumpWidget(_createTestApp(badgeContainer));
        await _pumpAndSettle(tester);

        // Badge should show the count
        expect(find.text('5'), findsOneWidget);

        badgeContainer.dispose();
      },
    );

    testWidgets(
      'Navigate to loteDetail via GoRouter and verify page renders',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        // Navigate programmatically to a detail route (simulates deep link)
        final router = container.read(goRouterProvider);
        router.goNamed(
          RouteNames.loteDetail,
          pathParameters: {'loteId': 'test-lote-42'},
        );
        await _pumpAndSettle(tester);

        // Verify the detail page renders with correct title
        expect(find.text('Detalhe do Lote'), findsOneWidget);
        expect(find.byType(AppBar), findsOneWidget);

        // The hamburger icon should still be present (ShellRoute)
        final drawerButton = find.byTooltip('Open navigation menu');
        expect(drawerButton, findsOneWidget);
      },
    );

    testWidgets(
      'Open drawer on loteDetail page and navigate back to Home',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        // Go to lote detail
        final router = container.read(goRouterProvider);
        router.goNamed(
          RouteNames.loteDetail,
          pathParameters: {'loteId': 'test-lote-42'},
        );
        await _pumpAndSettle(tester);
        expect(find.text('Detalhe do Lote'), findsOneWidget);

        // Open drawer from lote detail page
        await _tapHamburgerIcon(tester);

        // Drawer should show user info and menu items
        expect(find.text('Produtor Teste'), findsOneWidget);
        expect(find.text('Inicio'), findsOneWidget);

        // Tap "Inicio" to go back home
        await tester.tap(find.text('Inicio'));
        await _pumpAndSettle(tester);

        // Verify we are back on Home
        expect(find.text('eGranja'), findsOneWidget);
      },
    );

    testWidgets(
      'Drawer shows section headers when opened via hamburger tap',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        await _tapHamburgerIcon(tester);

        // Section headers (uppercase via .toUpperCase())
        expect(find.text('TAREFAS DIARIAS'), findsOneWidget);
        expect(find.text('MONITORAMENTO'), findsOneWidget);
        expect(find.text('SANIDADE'), findsOneWidget);
        expect(find.text('ANALISE'), findsOneWidget);
      },
    );

    testWidgets(
      'Drawer shows user info when opened via hamburger tap',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        await _tapHamburgerIcon(tester);

        // User name, initial, login, and type
        expect(find.text('Produtor Teste'), findsOneWidget);
        expect(find.text('P'), findsWidgets); // initial
        expect(find.text('produtor1'), findsOneWidget); // login
        expect(find.text('Produtor'), findsWidgets); // tipo label (may appear in drawer + home)
      },
    );

    testWidgets(
      'Navigate to multiple screens sequentially via drawer taps',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        // Route → expected title after navigation
        final drawerNavigations = <String, String>{
          'Checklist Diario': 'Checklist Diario',
          'IoT Sensores': 'Sensores IoT',
          'Relatorios': 'Relatorios',
          'Configuracoes': 'Configuracoes',
        };

        for (final entry in drawerNavigations.entries) {
          // Open drawer
          await _tapHamburgerIcon(tester);

          // Scroll to the item and tap it
          final itemFinder = find.text(entry.key);
          await tester.ensureVisible(itemFinder);
          await tester.tap(itemFinder);
          await _pumpAndSettle(tester);

          // Verify navigation
          expect(
            find.text(entry.value),
            findsWidgets,
            reason:
                'Expected "${entry.value}" after tapping "${entry.key}" in drawer',
          );
        }
      },
    );

    testWidgets(
      'Tapping "Sair" triggers logout flow',
      (tester) async {
        _useWideViewport(tester);
        await tester.pumpWidget(_createTestApp(container));
        await _pumpAndSettle(tester);

        // Open drawer
        await _tapHamburgerIcon(tester);

        // Scroll to "Sair" and tap it
        final sairFinder = find.text('Sair');
        await tester.ensureVisible(sairFinder);
        await tester.tap(sairFinder);
        await _pumpAndSettle(tester);

        // After logout, should redirect to login (TextFormField for
        // username/password should appear)
        expect(find.byType(TextFormField), findsWidgets);
      },
    );

    testWidgets(
      'Tecnico user sees "Produtores" in drawer and "PAINEL TECNICO" header',
      (tester) async {
        _useWideViewport(tester);
        final tecnicoContainer = _createContainer(
          authState: const AuthState(
            status: AuthStatus.authenticated,
            user: _testTecnico,
          ),
        );
        await tester.pumpWidget(_createTestApp(tecnicoContainer));
        await _pumpAndSettle(tester);

        await _tapHamburgerIcon(tester);

        // Tecnico sees different section header
        expect(find.text('PAINEL TECNICO'), findsOneWidget);
        // Tecnico sees "Produtores" menu item
        expect(find.text('Produtores'), findsOneWidget);
        // Tecnico should NOT see "Novo Lote" (only produtor sees that)
        expect(find.text('Novo Lote'), findsNothing);

        tecnicoContainer.dispose();
      },
    );
  });

  // ── Tests: Full ProviderScope Bootstrap ──────────────────────────────────

  group('Drawer Integration - Full Bootstrap (mirrors main.dart)', () {
    testWidgets(
      'Full ProviderScope bootstrap renders home and drawer without crashes',
      (tester) async {
        _useWideViewport(tester);

        // Build the app exactly as main.dart does:
        //   ProviderScope(child: Consumer → MaterialApp.router)
        //
        // The overrides simulate an authenticated user so the router
        // redirects to "/" instead of "/login".
        final app = _createFullBootstrapApp([
          authNotifierProvider.overrideWith(
            (_) => FakeAuthNotifier(
              const AuthState(
                status: AuthStatus.authenticated,
                user: _testUser,
              ),
            ),
          ),
          alertasProvider.overrideWith((_) => FakeAlertasNotifier()),
          alertasCountProvider.overrideWith((ref) => 0),
          syncProvider.overrideWith((_) => SyncNotifier(null)),
        ]);

        await tester.pumpWidget(app);
        await _pumpAndSettle(tester);

        // Should render home without "Null check operator" errors
        expect(find.text('eGranja'), findsOneWidget);
        expect(find.byType(AppBar), findsOneWidget);

        // Open drawer via hamburger tap
        await _tapHamburgerIcon(tester);

        // Drawer should render with user info and menu items
        expect(find.byType(Drawer), findsOneWidget);
        expect(find.text('Produtor Teste'), findsOneWidget);
        expect(find.text('Inicio'), findsOneWidget);
        expect(find.text('Granjas'), findsOneWidget);
      },
    );

    testWidgets(
      'Full bootstrap: drawer navigation works end-to-end',
      (tester) async {
        _useWideViewport(tester);

        final app = _createFullBootstrapApp([
          authNotifierProvider.overrideWith(
            (_) => FakeAuthNotifier(
              const AuthState(
                status: AuthStatus.authenticated,
                user: _testUser,
              ),
            ),
          ),
          alertasProvider.overrideWith((_) => FakeAlertasNotifier()),
          alertasCountProvider.overrideWith((ref) => 0),
          syncProvider.overrideWith((_) => SyncNotifier(null)),
        ]);

        await tester.pumpWidget(app);
        await _pumpAndSettle(tester);

        // Tap hamburger
        await _tapHamburgerIcon(tester);

        // Navigate to Checklist
        final checklistFinder = find.text('Checklist Diario');
        await tester.ensureVisible(checklistFinder);
        await tester.tap(checklistFinder);
        await _pumpAndSettle(tester);

        expect(find.text('Checklist Diario'), findsWidgets);

        // Open drawer again and navigate to Granjas
        await _tapHamburgerIcon(tester);
        final granjasFinder = find.text('Granjas');
        await tester.ensureVisible(granjasFinder);
        await tester.tap(granjasFinder);
        await _pumpAndSettle(tester);

        expect(find.text('Granjas'), findsWidgets);
      },
    );

    testWidgets(
      'Full bootstrap: notification icon tap does not crash',
      (tester) async {
        _useWideViewport(tester);

        final app = _createFullBootstrapApp([
          authNotifierProvider.overrideWith(
            (_) => FakeAuthNotifier(
              const AuthState(
                status: AuthStatus.authenticated,
                user: _testUser,
              ),
            ),
          ),
          alertasProvider.overrideWith((_) => FakeAlertasNotifier()),
          alertasCountProvider.overrideWith((ref) => 3),
          syncProvider.overrideWith((_) => SyncNotifier(null)),
        ]);

        await tester.pumpWidget(app);
        await _pumpAndSettle(tester);

        // Badge should appear
        expect(find.text('3'), findsOneWidget);

        // Tap notification icon
        await tester.tap(find.byIcon(Icons.notifications_outlined).first);
        await _pumpAndSettle(tester);

        // Should navigate to Alertas without crash
        expect(find.text('Alertas'), findsWidgets);
      },
    );

    testWidgets(
      'Full bootstrap with AppTheme: theme is applied correctly',
      (tester) async {
        _useWideViewport(tester);

        final app = _createFullBootstrapApp([
          authNotifierProvider.overrideWith(
            (_) => FakeAuthNotifier(
              const AuthState(
                status: AuthStatus.authenticated,
                user: _testUser,
              ),
            ),
          ),
          alertasProvider.overrideWith((_) => FakeAlertasNotifier()),
          alertasCountProvider.overrideWith((ref) => 0),
          syncProvider.overrideWith((_) => SyncNotifier(null)),
        ]);

        await tester.pumpWidget(app);
        await _pumpAndSettle(tester);

        // Verify the theme is applied (Material 3 AppBar)
        final appBar =
            tester.widget<AppBar>(find.byType(AppBar));
        expect(appBar, isNotNull);

        // Open drawer and verify it renders with the correct theme
        await _tapHamburgerIcon(tester);
        final drawer = tester.widget<Drawer>(find.byType(Drawer));
        expect(drawer, isNotNull);
      },
    );

    testWidgets(
      'Full bootstrap: navigating to loteDetail and back does not crash',
      (tester) async {
        _useWideViewport(tester);

        late ProviderContainer testContainer;

        final app = ProviderScope(
          overrides: [
            authNotifierProvider.overrideWith(
              (_) => FakeAuthNotifier(
                const AuthState(
                  status: AuthStatus.authenticated,
                  user: _testUser,
                ),
              ),
            ),
            alertasProvider.overrideWith((_) => FakeAlertasNotifier()),
            alertasCountProvider.overrideWith((ref) => 0),
            syncProvider.overrideWith((_) => SyncNotifier(null)),
          ],
          child: Consumer(
            builder: (context, ref, _) {
              testContainer = ProviderScope.containerOf(context);
              final router = ref.read(goRouterProvider);
              return MaterialApp.router(
                title: 'eGranja',
                theme: AppTheme.lightTheme,
                routerConfig: router,
                debugShowCheckedModeBanner: false,
              );
            },
          ),
        );

        await tester.pumpWidget(app);
        await _pumpAndSettle(tester);

        expect(find.text('eGranja'), findsOneWidget);

        // Navigate to lote detail
        final router = testContainer.read(goRouterProvider);
        router.goNamed(
          RouteNames.loteDetail,
          pathParameters: {'loteId': 'lote-abc-123'},
        );
        await _pumpAndSettle(tester);

        expect(find.text('Detalhe do Lote'), findsOneWidget);

        // Open drawer from lote detail and go back to Home
        await _tapHamburgerIcon(tester);
        expect(find.text('Inicio'), findsOneWidget);

        await tester.tap(find.text('Inicio'));
        await _pumpAndSettle(tester);

        expect(find.text('eGranja'), findsOneWidget);
      },
    );
  });
}
